//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace HospitalManager.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HospitalManagerDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HospitalManagerDBEntities object using the connection string found in the 'HospitalManagerDBEntities' section of the application configuration file.
        /// </summary>
        public HospitalManagerDBEntities() : base("name=HospitalManagerDBEntities", "HospitalManagerDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HospitalManagerDBEntities object.
        /// </summary>
        public HospitalManagerDBEntities(string connectionString) : base(connectionString, "HospitalManagerDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HospitalManagerDBEntities object.
        /// </summary>
        public HospitalManagerDBEntities(EntityConnection connection) : base(connection, "HospitalManagerDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USER> USERS
        {
            get
            {
                if ((_USERS == null))
                {
                    _USERS = base.CreateObjectSet<USER>("USERS");
                }
                return _USERS;
            }
        }
        private ObjectSet<USER> _USERS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USERS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSERS(USER uSER)
        {
            base.AddObject("USERS", uSER);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HospitalManagerDBModel", Name="USER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USER object.
        /// </summary>
        /// <param name="uSER_ID">Initial value of the USER_ID property.</param>
        /// <param name="fIRST_NAME">Initial value of the FIRST_NAME property.</param>
        /// <param name="lAST_NAME">Initial value of the LAST_NAME property.</param>
        /// <param name="sECURITY_ID">Initial value of the SECURITY_ID property.</param>
        /// <param name="uSER_TYPE">Initial value of the USER_TYPE property.</param>
        public static USER CreateUSER(global::System.Int32 uSER_ID, global::System.String fIRST_NAME, global::System.String lAST_NAME, global::System.Int32 sECURITY_ID, global::System.Int32 uSER_TYPE)
        {
            USER uSER = new USER();
            uSER.USER_ID = uSER_ID;
            uSER.FIRST_NAME = fIRST_NAME;
            uSER.LAST_NAME = lAST_NAME;
            uSER.SECURITY_ID = sECURITY_ID;
            uSER.USER_TYPE = uSER_TYPE;
            return uSER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 USER_ID
        {
            get
            {
                return _USER_ID;
            }
            set
            {
                if (_USER_ID != value)
                {
                    OnUSER_IDChanging(value);
                    ReportPropertyChanging("USER_ID");
                    _USER_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USER_ID");
                    OnUSER_IDChanged();
                }
            }
        }
        private global::System.Int32 _USER_ID;
        partial void OnUSER_IDChanging(global::System.Int32 value);
        partial void OnUSER_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIRST_NAME
        {
            get
            {
                return _FIRST_NAME;
            }
            set
            {
                OnFIRST_NAMEChanging(value);
                ReportPropertyChanging("FIRST_NAME");
                _FIRST_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIRST_NAME");
                OnFIRST_NAMEChanged();
            }
        }
        private global::System.String _FIRST_NAME;
        partial void OnFIRST_NAMEChanging(global::System.String value);
        partial void OnFIRST_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LAST_NAME
        {
            get
            {
                return _LAST_NAME;
            }
            set
            {
                OnLAST_NAMEChanging(value);
                ReportPropertyChanging("LAST_NAME");
                _LAST_NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LAST_NAME");
                OnLAST_NAMEChanged();
            }
        }
        private global::System.String _LAST_NAME;
        partial void OnLAST_NAMEChanging(global::System.String value);
        partial void OnLAST_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SECURITY_ID
        {
            get
            {
                return _SECURITY_ID;
            }
            set
            {
                OnSECURITY_IDChanging(value);
                ReportPropertyChanging("SECURITY_ID");
                _SECURITY_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SECURITY_ID");
                OnSECURITY_IDChanged();
            }
        }
        private global::System.Int32 _SECURITY_ID;
        partial void OnSECURITY_IDChanging(global::System.Int32 value);
        partial void OnSECURITY_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 USER_TYPE
        {
            get
            {
                return _USER_TYPE;
            }
            set
            {
                OnUSER_TYPEChanging(value);
                ReportPropertyChanging("USER_TYPE");
                _USER_TYPE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USER_TYPE");
                OnUSER_TYPEChanged();
            }
        }
        private global::System.Int32 _USER_TYPE;
        partial void OnUSER_TYPEChanging(global::System.Int32 value);
        partial void OnUSER_TYPEChanged();

        #endregion
    
    }

    #endregion
    
}
