#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManager.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HospitalManagerDB")]
	public partial class PastMedicalHistoryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFamilyCondition(FamilyCondition instance);
    partial void UpdateFamilyCondition(FamilyCondition instance);
    partial void DeleteFamilyCondition(FamilyCondition instance);
    partial void InsertFamilyMember(FamilyMember instance);
    partial void UpdateFamilyMember(FamilyMember instance);
    partial void DeleteFamilyMember(FamilyMember instance);
    partial void InsertPastMedicalHistory(PastMedicalHistory instance);
    partial void UpdatePastMedicalHistory(PastMedicalHistory instance);
    partial void DeletePastMedicalHistory(PastMedicalHistory instance);
    partial void InsertPatientCondition(PatientCondition instance);
    partial void UpdatePatientCondition(PatientCondition instance);
    partial void DeletePatientCondition(PatientCondition instance);
    partial void InsertMedicalCondition(MedicalCondition instance);
    partial void UpdateMedicalCondition(MedicalCondition instance);
    partial void DeleteMedicalCondition(MedicalCondition instance);
    #endregion
		
		public PastMedicalHistoryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PastMedicalHistoryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PastMedicalHistoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PastMedicalHistoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FamilyCondition> FamilyConditions
		{
			get
			{
				return this.GetTable<FamilyCondition>();
			}
		}
		
		public System.Data.Linq.Table<FamilyMember> FamilyMembers
		{
			get
			{
				return this.GetTable<FamilyMember>();
			}
		}
		
		public System.Data.Linq.Table<PastMedicalHistory> PastMedicalHistories
		{
			get
			{
				return this.GetTable<PastMedicalHistory>();
			}
		}
		
		public System.Data.Linq.Table<PatientCondition> PatientConditions
		{
			get
			{
				return this.GetTable<PatientCondition>();
			}
		}
		
		public System.Data.Linq.Table<MedicalCondition> MedicalConditions
		{
			get
			{
				return this.GetTable<MedicalCondition>();
			}
		}
		
		public System.Data.Linq.Table<OtherFamilyCondition> OtherFamilyConditions
		{
			get
			{
				return this.GetTable<OtherFamilyCondition>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FamilyConditions")]
	public partial class FamilyCondition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private int _FamilyMemberID;
		
		private int _ConditionID;
		
		private EntitySet<MedicalCondition> _MedicalConditions;
		
		private EntitySet<FamilyMember> _FamilyMembers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnFamilyMemberIDChanging(int value);
    partial void OnFamilyMemberIDChanged();
    partial void OnConditionIDChanging(int value);
    partial void OnConditionIDChanged();
    #endregion
		
		public FamilyCondition()
		{
			this._MedicalConditions = new EntitySet<MedicalCondition>(new Action<MedicalCondition>(this.attach_MedicalConditions), new Action<MedicalCondition>(this.detach_MedicalConditions));
			this._FamilyMembers = new EntitySet<FamilyMember>(new Action<FamilyMember>(this.attach_FamilyMembers), new Action<FamilyMember>(this.detach_FamilyMembers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyMemberID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FamilyMemberID
		{
			get
			{
				return this._FamilyMemberID;
			}
			set
			{
				if ((this._FamilyMemberID != value))
				{
					this.OnFamilyMemberIDChanging(value);
					this.SendPropertyChanging();
					this._FamilyMemberID = value;
					this.SendPropertyChanged("FamilyMemberID");
					this.OnFamilyMemberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConditionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ConditionID
		{
			get
			{
				return this._ConditionID;
			}
			set
			{
				if ((this._ConditionID != value))
				{
					this.OnConditionIDChanging(value);
					this.SendPropertyChanging();
					this._ConditionID = value;
					this.SendPropertyChanged("ConditionID");
					this.OnConditionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FamilyCondition_MedicalCondition", Storage="_MedicalConditions", ThisKey="ConditionID", OtherKey="ConditionID")]
		public EntitySet<MedicalCondition> MedicalConditions
		{
			get
			{
				return this._MedicalConditions;
			}
			set
			{
				this._MedicalConditions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FamilyCondition_FamilyMember", Storage="_FamilyMembers", ThisKey="FamilyMemberID", OtherKey="FamilyMemberID")]
		public EntitySet<FamilyMember> FamilyMembers
		{
			get
			{
				return this._FamilyMembers;
			}
			set
			{
				this._FamilyMembers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MedicalConditions(MedicalCondition entity)
		{
			this.SendPropertyChanging();
			entity.FamilyCondition = this;
		}
		
		private void detach_MedicalConditions(MedicalCondition entity)
		{
			this.SendPropertyChanging();
			entity.FamilyCondition = null;
		}
		
		private void attach_FamilyMembers(FamilyMember entity)
		{
			this.SendPropertyChanging();
			entity.FamilyCondition = this;
		}
		
		private void detach_FamilyMembers(FamilyMember entity)
		{
			this.SendPropertyChanging();
			entity.FamilyCondition = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FamilyMembers")]
	public partial class FamilyMember : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FamilyMemberID;
		
		private string _MemberName;
		
		private EntityRef<FamilyCondition> _FamilyCondition;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFamilyMemberIDChanging(int value);
    partial void OnFamilyMemberIDChanged();
    partial void OnMemberNameChanging(string value);
    partial void OnMemberNameChanged();
    #endregion
		
		public FamilyMember()
		{
			this._FamilyCondition = default(EntityRef<FamilyCondition>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyMemberID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FamilyMemberID
		{
			get
			{
				return this._FamilyMemberID;
			}
			set
			{
				if ((this._FamilyMemberID != value))
				{
					if (this._FamilyCondition.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFamilyMemberIDChanging(value);
					this.SendPropertyChanging();
					this._FamilyMemberID = value;
					this.SendPropertyChanged("FamilyMemberID");
					this.OnFamilyMemberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this.OnMemberNameChanging(value);
					this.SendPropertyChanging();
					this._MemberName = value;
					this.SendPropertyChanged("MemberName");
					this.OnMemberNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FamilyCondition_FamilyMember", Storage="_FamilyCondition", ThisKey="FamilyMemberID", OtherKey="FamilyMemberID", IsForeignKey=true)]
		public FamilyCondition FamilyCondition
		{
			get
			{
				return this._FamilyCondition.Entity;
			}
			set
			{
				FamilyCondition previousValue = this._FamilyCondition.Entity;
				if (((previousValue != value) 
							|| (this._FamilyCondition.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FamilyCondition.Entity = null;
						previousValue.FamilyMembers.Remove(this);
					}
					this._FamilyCondition.Entity = value;
					if ((value != null))
					{
						value.FamilyMembers.Add(this);
						this._FamilyMemberID = value.FamilyMemberID;
					}
					else
					{
						this._FamilyMemberID = default(int);
					}
					this.SendPropertyChanged("FamilyCondition");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PastMedicalHistories")]
	public partial class PastMedicalHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private int _Height;
		
		private int _Weight;
		
		private int _Age;
		
		private bool _Gender;
		
		private string _Ethnicity;
		
		private string _Allergies;
		
		private string _Operations;
		
		private string _OtherConditions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnHeightChanging(int value);
    partial void OnHeightChanged();
    partial void OnWeightChanging(int value);
    partial void OnWeightChanged();
    partial void OnAgeChanging(int value);
    partial void OnAgeChanged();
    partial void OnGenderChanging(bool value);
    partial void OnGenderChanged();
    partial void OnEthnicityChanging(string value);
    partial void OnEthnicityChanged();
    partial void OnAllergiesChanging(string value);
    partial void OnAllergiesChanged();
    partial void OnOperationsChanging(string value);
    partial void OnOperationsChanged();
    partial void OnOtherConditionsChanging(string value);
    partial void OnOtherConditionsChanged();
    #endregion
		
		public PastMedicalHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Int NOT NULL")]
		public int Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Int NOT NULL")]
		public int Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int NOT NULL")]
		public int Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit NOT NULL")]
		public bool Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ethnicity", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ethnicity
		{
			get
			{
				return this._Ethnicity;
			}
			set
			{
				if ((this._Ethnicity != value))
				{
					this.OnEthnicityChanging(value);
					this.SendPropertyChanging();
					this._Ethnicity = value;
					this.SendPropertyChanged("Ethnicity");
					this.OnEthnicityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Allergies", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Allergies
		{
			get
			{
				return this._Allergies;
			}
			set
			{
				if ((this._Allergies != value))
				{
					this.OnAllergiesChanging(value);
					this.SendPropertyChanging();
					this._Allergies = value;
					this.SendPropertyChanged("Allergies");
					this.OnAllergiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Operations", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Operations
		{
			get
			{
				return this._Operations;
			}
			set
			{
				if ((this._Operations != value))
				{
					this.OnOperationsChanging(value);
					this.SendPropertyChanging();
					this._Operations = value;
					this.SendPropertyChanged("Operations");
					this.OnOperationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherConditions", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string OtherConditions
		{
			get
			{
				return this._OtherConditions;
			}
			set
			{
				if ((this._OtherConditions != value))
				{
					this.OnOtherConditionsChanging(value);
					this.SendPropertyChanging();
					this._OtherConditions = value;
					this.SendPropertyChanged("OtherConditions");
					this.OnOtherConditionsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PatientConditions")]
	public partial class PatientCondition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private int _ConditionID;
		
		private EntitySet<MedicalCondition> _MedicalConditions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnConditionIDChanging(int value);
    partial void OnConditionIDChanged();
    #endregion
		
		public PatientCondition()
		{
			this._MedicalConditions = new EntitySet<MedicalCondition>(new Action<MedicalCondition>(this.attach_MedicalConditions), new Action<MedicalCondition>(this.detach_MedicalConditions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConditionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ConditionID
		{
			get
			{
				return this._ConditionID;
			}
			set
			{
				if ((this._ConditionID != value))
				{
					this.OnConditionIDChanging(value);
					this.SendPropertyChanging();
					this._ConditionID = value;
					this.SendPropertyChanged("ConditionID");
					this.OnConditionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PatientCondition_MedicalCondition", Storage="_MedicalConditions", ThisKey="ConditionID", OtherKey="ConditionID")]
		public EntitySet<MedicalCondition> MedicalConditions
		{
			get
			{
				return this._MedicalConditions;
			}
			set
			{
				this._MedicalConditions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MedicalConditions(MedicalCondition entity)
		{
			this.SendPropertyChanging();
			entity.PatientCondition = this;
		}
		
		private void detach_MedicalConditions(MedicalCondition entity)
		{
			this.SendPropertyChanging();
			entity.PatientCondition = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MedicalConditions")]
	public partial class MedicalCondition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ConditionID;
		
		private string _ConditionName;
		
		private EntityRef<PatientCondition> _PatientCondition;
		
		private EntityRef<FamilyCondition> _FamilyCondition;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnConditionIDChanging(int value);
    partial void OnConditionIDChanged();
    partial void OnConditionNameChanging(string value);
    partial void OnConditionNameChanged();
    #endregion
		
		public MedicalCondition()
		{
			this._PatientCondition = default(EntityRef<PatientCondition>);
			this._FamilyCondition = default(EntityRef<FamilyCondition>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConditionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ConditionID
		{
			get
			{
				return this._ConditionID;
			}
			set
			{
				if ((this._ConditionID != value))
				{
					if ((this._PatientCondition.HasLoadedOrAssignedValue || this._FamilyCondition.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnConditionIDChanging(value);
					this.SendPropertyChanging();
					this._ConditionID = value;
					this.SendPropertyChanged("ConditionID");
					this.OnConditionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConditionName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ConditionName
		{
			get
			{
				return this._ConditionName;
			}
			set
			{
				if ((this._ConditionName != value))
				{
					this.OnConditionNameChanging(value);
					this.SendPropertyChanging();
					this._ConditionName = value;
					this.SendPropertyChanged("ConditionName");
					this.OnConditionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PatientCondition_MedicalCondition", Storage="_PatientCondition", ThisKey="ConditionID", OtherKey="ConditionID", IsForeignKey=true)]
		public PatientCondition PatientCondition
		{
			get
			{
				return this._PatientCondition.Entity;
			}
			set
			{
				PatientCondition previousValue = this._PatientCondition.Entity;
				if (((previousValue != value) 
							|| (this._PatientCondition.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PatientCondition.Entity = null;
						previousValue.MedicalConditions.Remove(this);
					}
					this._PatientCondition.Entity = value;
					if ((value != null))
					{
						value.MedicalConditions.Add(this);
						this._ConditionID = value.ConditionID;
					}
					else
					{
						this._ConditionID = default(int);
					}
					this.SendPropertyChanged("PatientCondition");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FamilyCondition_MedicalCondition", Storage="_FamilyCondition", ThisKey="ConditionID", OtherKey="ConditionID", IsForeignKey=true)]
		public FamilyCondition FamilyCondition
		{
			get
			{
				return this._FamilyCondition.Entity;
			}
			set
			{
				FamilyCondition previousValue = this._FamilyCondition.Entity;
				if (((previousValue != value) 
							|| (this._FamilyCondition.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FamilyCondition.Entity = null;
						previousValue.MedicalConditions.Remove(this);
					}
					this._FamilyCondition.Entity = value;
					if ((value != null))
					{
						value.MedicalConditions.Add(this);
						this._ConditionID = value.ConditionID;
					}
					else
					{
						this._ConditionID = default(int);
					}
					this.SendPropertyChanged("FamilyCondition");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OtherFamilyConditions")]
	public partial class OtherFamilyCondition
	{
		
		private int _UserID;
		
		private int _FamilyMemberID;
		
		private string _Condition;
		
		public OtherFamilyCondition()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyMemberID", DbType="Int NOT NULL")]
		public int FamilyMemberID
		{
			get
			{
				return this._FamilyMemberID;
			}
			set
			{
				if ((this._FamilyMemberID != value))
				{
					this._FamilyMemberID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Condition", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Condition
		{
			get
			{
				return this._Condition;
			}
			set
			{
				if ((this._Condition != value))
				{
					this._Condition = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
