<?xml version="1.0" encoding="utf-8"?><Database Name="HospitalManagerDB" Class="ScheduleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\HospitalManagerDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HospitalManagerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="ScheduleUsers">
    <Type Name="ScheduleUsers">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="User_Schedule" Member="Schedules" ThisKey="UserID" OtherKey="UserID" Type="Schedule" />
    </Type>
  </Table>
  <Table Name="dbo.Schedules" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Month" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[0900]" Member="_0900" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[0930]" Member="_0930" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1000]" Member="_1000" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1030]" Member="_1030" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1100]" Member="_1100" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1130]" Member="_1130" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1200]" Member="_1200" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1230]" Member="_1230" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1300]" Member="_1300" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1330]" Member="_1330" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1400]" Member="_1400" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1430]" Member="_1430" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1500]" Member="_1500" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1530]" Member="_1530" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1600]" Member="_1600" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1630]" Member="_1630" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Schedule" Member="ScheduleUsers" Storage="_User" ThisKey="UserID" OtherKey="UserID" Type="ScheduleUsers" IsForeignKey="true" />
    </Type>
  </Table>
</Database>