#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManager.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HospitalManagerDB")]
	public partial class ScheduleDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertScheduleUsers(ScheduleUsers instance);
    partial void UpdateScheduleUsers(ScheduleUsers instance);
    partial void DeleteScheduleUsers(ScheduleUsers instance);
    partial void InsertSchedule(Schedule instance);
    partial void UpdateSchedule(Schedule instance);
    partial void DeleteSchedule(Schedule instance);
    #endregion
		
		public ScheduleDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HospitalManagerDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ScheduleUsers> ScheduleUsers
		{
			get
			{
				return this.GetTable<ScheduleUsers>();
			}
		}
		
		public System.Data.Linq.Table<Schedule> Schedules
		{
			get
			{
				return this.GetTable<Schedule>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class ScheduleUsers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private int _TypeID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Email;
		
		private EntitySet<Schedule> _Schedules;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnTypeIDChanging(int value);
    partial void OnTypeIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public ScheduleUsers()
		{
			this._Schedules = new EntitySet<Schedule>(new Action<Schedule>(this.attach_Schedules), new Action<Schedule>(this.detach_Schedules));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeID", DbType="Int NOT NULL")]
		public int TypeID
		{
			get
			{
				return this._TypeID;
			}
			set
			{
				if ((this._TypeID != value))
				{
					this.OnTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TypeID = value;
					this.SendPropertyChanged("TypeID");
					this.OnTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ScheduleUsers_Schedule", Storage="_Schedules", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<Schedule> Schedules
		{
			get
			{
				return this._Schedules;
			}
			set
			{
				this._Schedules.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Schedules(Schedule entity)
		{
			this.SendPropertyChanging();
			entity.ScheduleUsers = this;
		}
		
		private void detach_Schedules(Schedule entity)
		{
			this.SendPropertyChanging();
			entity.ScheduleUsers = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Schedules")]
	public partial class Schedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Month;
		
		private int _Day;
		
		private int _Year;
		
		private System.Nullable<int> @__0900;
		
		private System.Nullable<int> @__0930;
		
		private System.Nullable<int> @__1000;
		
		private System.Nullable<int> @__1030;
		
		private System.Nullable<int> @__1100;
		
		private System.Nullable<int> @__1130;
		
		private System.Nullable<int> @__1200;
		
		private System.Nullable<int> @__1230;
		
		private System.Nullable<int> @__1300;
		
		private System.Nullable<int> @__1330;
		
		private System.Nullable<int> @__1400;
		
		private System.Nullable<int> @__1430;
		
		private System.Nullable<int> @__1500;
		
		private System.Nullable<int> @__1530;
		
		private System.Nullable<int> @__1600;
		
		private System.Nullable<int> @__1630;
		
		private EntityRef<ScheduleUsers> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnMonthChanging(string value);
    partial void OnMonthChanged();
    partial void OnDayChanging(int value);
    partial void OnDayChanged();
    partial void OnYearChanging(int value);
    partial void OnYearChanged();
    partial void On_0900Changing(System.Nullable<int> value);
    partial void On_0900Changed();
    partial void On_0930Changing(System.Nullable<int> value);
    partial void On_0930Changed();
    partial void On_1000Changing(System.Nullable<int> value);
    partial void On_1000Changed();
    partial void On_1030Changing(System.Nullable<int> value);
    partial void On_1030Changed();
    partial void On_1100Changing(System.Nullable<int> value);
    partial void On_1100Changed();
    partial void On_1130Changing(System.Nullable<int> value);
    partial void On_1130Changed();
    partial void On_1200Changing(System.Nullable<int> value);
    partial void On_1200Changed();
    partial void On_1230Changing(System.Nullable<int> value);
    partial void On_1230Changed();
    partial void On_1300Changing(System.Nullable<int> value);
    partial void On_1300Changed();
    partial void On_1330Changing(System.Nullable<int> value);
    partial void On_1330Changed();
    partial void On_1400Changing(System.Nullable<int> value);
    partial void On_1400Changed();
    partial void On_1430Changing(System.Nullable<int> value);
    partial void On_1430Changed();
    partial void On_1500Changing(System.Nullable<int> value);
    partial void On_1500Changed();
    partial void On_1530Changing(System.Nullable<int> value);
    partial void On_1530Changed();
    partial void On_1600Changing(System.Nullable<int> value);
    partial void On_1600Changed();
    partial void On_1630Changing(System.Nullable<int> value);
    partial void On_1630Changed();
    #endregion
		
		public Schedule()
		{
			this._User = default(EntityRef<ScheduleUsers>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0900]", Storage="__0900", DbType="Int")]
		public System.Nullable<int> _0900
		{
			get
			{
				return this.@__0900;
			}
			set
			{
				if ((this.@__0900 != value))
				{
					this.On_0900Changing(value);
					this.SendPropertyChanging();
					this.@__0900 = value;
					this.SendPropertyChanged("_0900");
					this.On_0900Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0930]", Storage="__0930", DbType="Int")]
		public System.Nullable<int> _0930
		{
			get
			{
				return this.@__0930;
			}
			set
			{
				if ((this.@__0930 != value))
				{
					this.On_0930Changing(value);
					this.SendPropertyChanging();
					this.@__0930 = value;
					this.SendPropertyChanged("_0930");
					this.On_0930Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1000]", Storage="__1000", DbType="Int")]
		public System.Nullable<int> _1000
		{
			get
			{
				return this.@__1000;
			}
			set
			{
				if ((this.@__1000 != value))
				{
					this.On_1000Changing(value);
					this.SendPropertyChanging();
					this.@__1000 = value;
					this.SendPropertyChanged("_1000");
					this.On_1000Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1030]", Storage="__1030", DbType="Int")]
		public System.Nullable<int> _1030
		{
			get
			{
				return this.@__1030;
			}
			set
			{
				if ((this.@__1030 != value))
				{
					this.On_1030Changing(value);
					this.SendPropertyChanging();
					this.@__1030 = value;
					this.SendPropertyChanged("_1030");
					this.On_1030Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1100]", Storage="__1100", DbType="Int")]
		public System.Nullable<int> _1100
		{
			get
			{
				return this.@__1100;
			}
			set
			{
				if ((this.@__1100 != value))
				{
					this.On_1100Changing(value);
					this.SendPropertyChanging();
					this.@__1100 = value;
					this.SendPropertyChanged("_1100");
					this.On_1100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1130]", Storage="__1130", DbType="Int")]
		public System.Nullable<int> _1130
		{
			get
			{
				return this.@__1130;
			}
			set
			{
				if ((this.@__1130 != value))
				{
					this.On_1130Changing(value);
					this.SendPropertyChanging();
					this.@__1130 = value;
					this.SendPropertyChanged("_1130");
					this.On_1130Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1200]", Storage="__1200", DbType="Int")]
		public System.Nullable<int> _1200
		{
			get
			{
				return this.@__1200;
			}
			set
			{
				if ((this.@__1200 != value))
				{
					this.On_1200Changing(value);
					this.SendPropertyChanging();
					this.@__1200 = value;
					this.SendPropertyChanged("_1200");
					this.On_1200Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1230]", Storage="__1230", DbType="Int")]
		public System.Nullable<int> _1230
		{
			get
			{
				return this.@__1230;
			}
			set
			{
				if ((this.@__1230 != value))
				{
					this.On_1230Changing(value);
					this.SendPropertyChanging();
					this.@__1230 = value;
					this.SendPropertyChanged("_1230");
					this.On_1230Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1300]", Storage="__1300", DbType="Int")]
		public System.Nullable<int> _1300
		{
			get
			{
				return this.@__1300;
			}
			set
			{
				if ((this.@__1300 != value))
				{
					this.On_1300Changing(value);
					this.SendPropertyChanging();
					this.@__1300 = value;
					this.SendPropertyChanged("_1300");
					this.On_1300Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1330]", Storage="__1330", DbType="Int")]
		public System.Nullable<int> _1330
		{
			get
			{
				return this.@__1330;
			}
			set
			{
				if ((this.@__1330 != value))
				{
					this.On_1330Changing(value);
					this.SendPropertyChanging();
					this.@__1330 = value;
					this.SendPropertyChanged("_1330");
					this.On_1330Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1400]", Storage="__1400", DbType="Int")]
		public System.Nullable<int> _1400
		{
			get
			{
				return this.@__1400;
			}
			set
			{
				if ((this.@__1400 != value))
				{
					this.On_1400Changing(value);
					this.SendPropertyChanging();
					this.@__1400 = value;
					this.SendPropertyChanged("_1400");
					this.On_1400Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1430]", Storage="__1430", DbType="Int")]
		public System.Nullable<int> _1430
		{
			get
			{
				return this.@__1430;
			}
			set
			{
				if ((this.@__1430 != value))
				{
					this.On_1430Changing(value);
					this.SendPropertyChanging();
					this.@__1430 = value;
					this.SendPropertyChanged("_1430");
					this.On_1430Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1500]", Storage="__1500", DbType="Int")]
		public System.Nullable<int> _1500
		{
			get
			{
				return this.@__1500;
			}
			set
			{
				if ((this.@__1500 != value))
				{
					this.On_1500Changing(value);
					this.SendPropertyChanging();
					this.@__1500 = value;
					this.SendPropertyChanged("_1500");
					this.On_1500Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1530]", Storage="__1530", DbType="Int")]
		public System.Nullable<int> _1530
		{
			get
			{
				return this.@__1530;
			}
			set
			{
				if ((this.@__1530 != value))
				{
					this.On_1530Changing(value);
					this.SendPropertyChanging();
					this.@__1530 = value;
					this.SendPropertyChanged("_1530");
					this.On_1530Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1600]", Storage="__1600", DbType="Int")]
		public System.Nullable<int> _1600
		{
			get
			{
				return this.@__1600;
			}
			set
			{
				if ((this.@__1600 != value))
				{
					this.On_1600Changing(value);
					this.SendPropertyChanging();
					this.@__1600 = value;
					this.SendPropertyChanged("_1600");
					this.On_1600Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1630]", Storage="__1630", DbType="Int")]
		public System.Nullable<int> _1630
		{
			get
			{
				return this.@__1630;
			}
			set
			{
				if ((this.@__1630 != value))
				{
					this.On_1630Changing(value);
					this.SendPropertyChanging();
					this.@__1630 = value;
					this.SendPropertyChanged("_1630");
					this.On_1630Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ScheduleUsers_Schedule", Storage="_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public ScheduleUsers ScheduleUsers
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				ScheduleUsers previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Schedules.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Schedules.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("ScheduleUsers");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
