#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManager.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HospitalManagerDB")]
	public partial class SchedulesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFeb(Feb instance);
    partial void UpdateFeb(Feb instance);
    partial void DeleteFeb(Feb instance);
    partial void InsertJan(Jan instance);
    partial void UpdateJan(Jan instance);
    partial void DeleteJan(Jan instance);
    #endregion
		
		public SchedulesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HospitalManagerDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SchedulesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchedulesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchedulesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchedulesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Apr> Aprs
		{
			get
			{
				return this.GetTable<Apr>();
			}
		}
		
		public System.Data.Linq.Table<Feb> Febs
		{
			get
			{
				return this.GetTable<Feb>();
			}
		}
		
		public System.Data.Linq.Table<Jan> Jans
		{
			get
			{
				return this.GetTable<Jan>();
			}
		}
		
		public System.Data.Linq.Table<Jun> Juns
		{
			get
			{
				return this.GetTable<Jun>();
			}
		}
		
		public System.Data.Linq.Table<Mar> Mars
		{
			get
			{
				return this.GetTable<Mar>();
			}
		}
		
		public System.Data.Linq.Table<May> Mays
		{
			get
			{
				return this.GetTable<May>();
			}
		}
		
		public System.Data.Linq.Table<Doctors> Doctors
		{
			get
			{
				return this.GetTable<Doctors>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Apr")]
	public partial class Apr
	{
		
		private int _StaffID;
		
		private System.DateTime _Date;
		
		private System.Nullable<int> @__0900;
		
		private System.Nullable<int> @__0930;
		
		private System.Nullable<int> @__1000;
		
		private System.Nullable<int> @__1030;
		
		private System.Nullable<int> @__1100;
		
		private System.Nullable<int> @__1130;
		
		private System.Nullable<int> @__1200;
		
		private System.Nullable<int> @__1230;
		
		private System.Nullable<int> @__1300;
		
		private System.Nullable<int> @__1330;
		
		private System.Nullable<int> @__1400;
		
		private System.Nullable<int> @__1430;
		
		private System.Nullable<int> @__1500;
		
		private System.Nullable<int> @__1530;
		
		private System.Nullable<int> @__1600;
		
		private System.Nullable<int> @__1630;
		
		public Apr()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="Int NOT NULL")]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this._StaffID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0900]", Storage="__0900", DbType="Int")]
		public System.Nullable<int> _0900
		{
			get
			{
				return this.@__0900;
			}
			set
			{
				if ((this.@__0900 != value))
				{
					this.@__0900 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0930]", Storage="__0930", DbType="Int")]
		public System.Nullable<int> _0930
		{
			get
			{
				return this.@__0930;
			}
			set
			{
				if ((this.@__0930 != value))
				{
					this.@__0930 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1000]", Storage="__1000", DbType="Int")]
		public System.Nullable<int> _1000
		{
			get
			{
				return this.@__1000;
			}
			set
			{
				if ((this.@__1000 != value))
				{
					this.@__1000 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1030]", Storage="__1030", DbType="Int")]
		public System.Nullable<int> _1030
		{
			get
			{
				return this.@__1030;
			}
			set
			{
				if ((this.@__1030 != value))
				{
					this.@__1030 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1100]", Storage="__1100", DbType="Int")]
		public System.Nullable<int> _1100
		{
			get
			{
				return this.@__1100;
			}
			set
			{
				if ((this.@__1100 != value))
				{
					this.@__1100 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1130]", Storage="__1130", DbType="Int")]
		public System.Nullable<int> _1130
		{
			get
			{
				return this.@__1130;
			}
			set
			{
				if ((this.@__1130 != value))
				{
					this.@__1130 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1200]", Storage="__1200", DbType="Int")]
		public System.Nullable<int> _1200
		{
			get
			{
				return this.@__1200;
			}
			set
			{
				if ((this.@__1200 != value))
				{
					this.@__1200 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1230]", Storage="__1230", DbType="Int")]
		public System.Nullable<int> _1230
		{
			get
			{
				return this.@__1230;
			}
			set
			{
				if ((this.@__1230 != value))
				{
					this.@__1230 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1300]", Storage="__1300", DbType="Int")]
		public System.Nullable<int> _1300
		{
			get
			{
				return this.@__1300;
			}
			set
			{
				if ((this.@__1300 != value))
				{
					this.@__1300 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1330]", Storage="__1330", DbType="Int")]
		public System.Nullable<int> _1330
		{
			get
			{
				return this.@__1330;
			}
			set
			{
				if ((this.@__1330 != value))
				{
					this.@__1330 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1400]", Storage="__1400", DbType="Int")]
		public System.Nullable<int> _1400
		{
			get
			{
				return this.@__1400;
			}
			set
			{
				if ((this.@__1400 != value))
				{
					this.@__1400 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1430]", Storage="__1430", DbType="Int")]
		public System.Nullable<int> _1430
		{
			get
			{
				return this.@__1430;
			}
			set
			{
				if ((this.@__1430 != value))
				{
					this.@__1430 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1500]", Storage="__1500", DbType="Int")]
		public System.Nullable<int> _1500
		{
			get
			{
				return this.@__1500;
			}
			set
			{
				if ((this.@__1500 != value))
				{
					this.@__1500 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1530]", Storage="__1530", DbType="Int")]
		public System.Nullable<int> _1530
		{
			get
			{
				return this.@__1530;
			}
			set
			{
				if ((this.@__1530 != value))
				{
					this.@__1530 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1600]", Storage="__1600", DbType="Int")]
		public System.Nullable<int> _1600
		{
			get
			{
				return this.@__1600;
			}
			set
			{
				if ((this.@__1600 != value))
				{
					this.@__1600 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1630]", Storage="__1630", DbType="Int")]
		public System.Nullable<int> _1630
		{
			get
			{
				return this.@__1630;
			}
			set
			{
				if ((this.@__1630 != value))
				{
					this.@__1630 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Feb")]
	public partial class Feb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StaffID;
		
		private System.DateTime _Date;
		
		private System.Nullable<int> @__0900;
		
		private System.Nullable<int> @__0930;
		
		private System.Nullable<int> @__1000;
		
		private System.Nullable<int> @__1030;
		
		private System.Nullable<int> @__1100;
		
		private System.Nullable<int> @__1130;
		
		private System.Nullable<int> @__1200;
		
		private System.Nullable<int> @__1230;
		
		private System.Nullable<int> @__1300;
		
		private System.Nullable<int> @__1330;
		
		private System.Nullable<int> @__1400;
		
		private System.Nullable<int> @__1430;
		
		private System.Nullable<int> @__1500;
		
		private System.Nullable<int> @__1530;
		
		private System.Nullable<int> @__1600;
		
		private System.Nullable<int> @__1630;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaffIDChanging(int value);
    partial void OnStaffIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void On_0900Changing(System.Nullable<int> value);
    partial void On_0900Changed();
    partial void On_0930Changing(System.Nullable<int> value);
    partial void On_0930Changed();
    partial void On_1000Changing(System.Nullable<int> value);
    partial void On_1000Changed();
    partial void On_1030Changing(System.Nullable<int> value);
    partial void On_1030Changed();
    partial void On_1100Changing(System.Nullable<int> value);
    partial void On_1100Changed();
    partial void On_1130Changing(System.Nullable<int> value);
    partial void On_1130Changed();
    partial void On_1200Changing(System.Nullable<int> value);
    partial void On_1200Changed();
    partial void On_1230Changing(System.Nullable<int> value);
    partial void On_1230Changed();
    partial void On_1300Changing(System.Nullable<int> value);
    partial void On_1300Changed();
    partial void On_1330Changing(System.Nullable<int> value);
    partial void On_1330Changed();
    partial void On_1400Changing(System.Nullable<int> value);
    partial void On_1400Changed();
    partial void On_1430Changing(System.Nullable<int> value);
    partial void On_1430Changed();
    partial void On_1500Changing(System.Nullable<int> value);
    partial void On_1500Changed();
    partial void On_1530Changing(System.Nullable<int> value);
    partial void On_1530Changed();
    partial void On_1600Changing(System.Nullable<int> value);
    partial void On_1600Changed();
    partial void On_1630Changing(System.Nullable<int> value);
    partial void On_1630Changed();
    #endregion
		
		public Feb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this.OnStaffIDChanging(value);
					this.SendPropertyChanging();
					this._StaffID = value;
					this.SendPropertyChanged("StaffID");
					this.OnStaffIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0900]", Storage="__0900", DbType="Int")]
		public System.Nullable<int> _0900
		{
			get
			{
				return this.@__0900;
			}
			set
			{
				if ((this.@__0900 != value))
				{
					this.On_0900Changing(value);
					this.SendPropertyChanging();
					this.@__0900 = value;
					this.SendPropertyChanged("_0900");
					this.On_0900Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0930]", Storage="__0930", DbType="Int")]
		public System.Nullable<int> _0930
		{
			get
			{
				return this.@__0930;
			}
			set
			{
				if ((this.@__0930 != value))
				{
					this.On_0930Changing(value);
					this.SendPropertyChanging();
					this.@__0930 = value;
					this.SendPropertyChanged("_0930");
					this.On_0930Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1000]", Storage="__1000", DbType="Int")]
		public System.Nullable<int> _1000
		{
			get
			{
				return this.@__1000;
			}
			set
			{
				if ((this.@__1000 != value))
				{
					this.On_1000Changing(value);
					this.SendPropertyChanging();
					this.@__1000 = value;
					this.SendPropertyChanged("_1000");
					this.On_1000Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1030]", Storage="__1030", DbType="Int")]
		public System.Nullable<int> _1030
		{
			get
			{
				return this.@__1030;
			}
			set
			{
				if ((this.@__1030 != value))
				{
					this.On_1030Changing(value);
					this.SendPropertyChanging();
					this.@__1030 = value;
					this.SendPropertyChanged("_1030");
					this.On_1030Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1100]", Storage="__1100", DbType="Int")]
		public System.Nullable<int> _1100
		{
			get
			{
				return this.@__1100;
			}
			set
			{
				if ((this.@__1100 != value))
				{
					this.On_1100Changing(value);
					this.SendPropertyChanging();
					this.@__1100 = value;
					this.SendPropertyChanged("_1100");
					this.On_1100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1130]", Storage="__1130", DbType="Int")]
		public System.Nullable<int> _1130
		{
			get
			{
				return this.@__1130;
			}
			set
			{
				if ((this.@__1130 != value))
				{
					this.On_1130Changing(value);
					this.SendPropertyChanging();
					this.@__1130 = value;
					this.SendPropertyChanged("_1130");
					this.On_1130Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1200]", Storage="__1200", DbType="Int")]
		public System.Nullable<int> _1200
		{
			get
			{
				return this.@__1200;
			}
			set
			{
				if ((this.@__1200 != value))
				{
					this.On_1200Changing(value);
					this.SendPropertyChanging();
					this.@__1200 = value;
					this.SendPropertyChanged("_1200");
					this.On_1200Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1230]", Storage="__1230", DbType="Int")]
		public System.Nullable<int> _1230
		{
			get
			{
				return this.@__1230;
			}
			set
			{
				if ((this.@__1230 != value))
				{
					this.On_1230Changing(value);
					this.SendPropertyChanging();
					this.@__1230 = value;
					this.SendPropertyChanged("_1230");
					this.On_1230Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1300]", Storage="__1300", DbType="Int")]
		public System.Nullable<int> _1300
		{
			get
			{
				return this.@__1300;
			}
			set
			{
				if ((this.@__1300 != value))
				{
					this.On_1300Changing(value);
					this.SendPropertyChanging();
					this.@__1300 = value;
					this.SendPropertyChanged("_1300");
					this.On_1300Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1330]", Storage="__1330", DbType="Int")]
		public System.Nullable<int> _1330
		{
			get
			{
				return this.@__1330;
			}
			set
			{
				if ((this.@__1330 != value))
				{
					this.On_1330Changing(value);
					this.SendPropertyChanging();
					this.@__1330 = value;
					this.SendPropertyChanged("_1330");
					this.On_1330Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1400]", Storage="__1400", DbType="Int")]
		public System.Nullable<int> _1400
		{
			get
			{
				return this.@__1400;
			}
			set
			{
				if ((this.@__1400 != value))
				{
					this.On_1400Changing(value);
					this.SendPropertyChanging();
					this.@__1400 = value;
					this.SendPropertyChanged("_1400");
					this.On_1400Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1430]", Storage="__1430", DbType="Int")]
		public System.Nullable<int> _1430
		{
			get
			{
				return this.@__1430;
			}
			set
			{
				if ((this.@__1430 != value))
				{
					this.On_1430Changing(value);
					this.SendPropertyChanging();
					this.@__1430 = value;
					this.SendPropertyChanged("_1430");
					this.On_1430Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1500]", Storage="__1500", DbType="Int")]
		public System.Nullable<int> _1500
		{
			get
			{
				return this.@__1500;
			}
			set
			{
				if ((this.@__1500 != value))
				{
					this.On_1500Changing(value);
					this.SendPropertyChanging();
					this.@__1500 = value;
					this.SendPropertyChanged("_1500");
					this.On_1500Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1530]", Storage="__1530", DbType="Int")]
		public System.Nullable<int> _1530
		{
			get
			{
				return this.@__1530;
			}
			set
			{
				if ((this.@__1530 != value))
				{
					this.On_1530Changing(value);
					this.SendPropertyChanging();
					this.@__1530 = value;
					this.SendPropertyChanged("_1530");
					this.On_1530Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1600]", Storage="__1600", DbType="Int")]
		public System.Nullable<int> _1600
		{
			get
			{
				return this.@__1600;
			}
			set
			{
				if ((this.@__1600 != value))
				{
					this.On_1600Changing(value);
					this.SendPropertyChanging();
					this.@__1600 = value;
					this.SendPropertyChanged("_1600");
					this.On_1600Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1630]", Storage="__1630", DbType="Int")]
		public System.Nullable<int> _1630
		{
			get
			{
				return this.@__1630;
			}
			set
			{
				if ((this.@__1630 != value))
				{
					this.On_1630Changing(value);
					this.SendPropertyChanging();
					this.@__1630 = value;
					this.SendPropertyChanged("_1630");
					this.On_1630Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jan")]
	public partial class Jan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StaffID;
		
		private System.DateTime _Date;
		
		private System.Nullable<int> @__0900;
		
		private System.Nullable<int> @__0930;
		
		private System.Nullable<int> @__1000;
		
		private System.Nullable<int> @__1030;
		
		private System.Nullable<int> @__1100;
		
		private System.Nullable<int> @__1130;
		
		private System.Nullable<int> @__1200;
		
		private System.Nullable<int> @__1230;
		
		private System.Nullable<int> @__1300;
		
		private System.Nullable<int> @__1330;
		
		private System.Nullable<int> @__1400;
		
		private System.Nullable<int> @__1430;
		
		private System.Nullable<int> @__1500;
		
		private System.Nullable<int> @__1530;
		
		private System.Nullable<int> @__1600;
		
		private System.Nullable<int> @__1630;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaffIDChanging(int value);
    partial void OnStaffIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void On_0900Changing(System.Nullable<int> value);
    partial void On_0900Changed();
    partial void On_0930Changing(System.Nullable<int> value);
    partial void On_0930Changed();
    partial void On_1000Changing(System.Nullable<int> value);
    partial void On_1000Changed();
    partial void On_1030Changing(System.Nullable<int> value);
    partial void On_1030Changed();
    partial void On_1100Changing(System.Nullable<int> value);
    partial void On_1100Changed();
    partial void On_1130Changing(System.Nullable<int> value);
    partial void On_1130Changed();
    partial void On_1200Changing(System.Nullable<int> value);
    partial void On_1200Changed();
    partial void On_1230Changing(System.Nullable<int> value);
    partial void On_1230Changed();
    partial void On_1300Changing(System.Nullable<int> value);
    partial void On_1300Changed();
    partial void On_1330Changing(System.Nullable<int> value);
    partial void On_1330Changed();
    partial void On_1400Changing(System.Nullable<int> value);
    partial void On_1400Changed();
    partial void On_1430Changing(System.Nullable<int> value);
    partial void On_1430Changed();
    partial void On_1500Changing(System.Nullable<int> value);
    partial void On_1500Changed();
    partial void On_1530Changing(System.Nullable<int> value);
    partial void On_1530Changed();
    partial void On_1600Changing(System.Nullable<int> value);
    partial void On_1600Changed();
    partial void On_1630Changing(System.Nullable<int> value);
    partial void On_1630Changed();
    #endregion
		
		public Jan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this.OnStaffIDChanging(value);
					this.SendPropertyChanging();
					this._StaffID = value;
					this.SendPropertyChanged("StaffID");
					this.OnStaffIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0900]", Storage="__0900", DbType="Int")]
		public System.Nullable<int> _0900
		{
			get
			{
				return this.@__0900;
			}
			set
			{
				if ((this.@__0900 != value))
				{
					this.On_0900Changing(value);
					this.SendPropertyChanging();
					this.@__0900 = value;
					this.SendPropertyChanged("_0900");
					this.On_0900Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0930]", Storage="__0930", DbType="Int")]
		public System.Nullable<int> _0930
		{
			get
			{
				return this.@__0930;
			}
			set
			{
				if ((this.@__0930 != value))
				{
					this.On_0930Changing(value);
					this.SendPropertyChanging();
					this.@__0930 = value;
					this.SendPropertyChanged("_0930");
					this.On_0930Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1000]", Storage="__1000", DbType="Int")]
		public System.Nullable<int> _1000
		{
			get
			{
				return this.@__1000;
			}
			set
			{
				if ((this.@__1000 != value))
				{
					this.On_1000Changing(value);
					this.SendPropertyChanging();
					this.@__1000 = value;
					this.SendPropertyChanged("_1000");
					this.On_1000Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1030]", Storage="__1030", DbType="Int")]
		public System.Nullable<int> _1030
		{
			get
			{
				return this.@__1030;
			}
			set
			{
				if ((this.@__1030 != value))
				{
					this.On_1030Changing(value);
					this.SendPropertyChanging();
					this.@__1030 = value;
					this.SendPropertyChanged("_1030");
					this.On_1030Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1100]", Storage="__1100", DbType="Int")]
		public System.Nullable<int> _1100
		{
			get
			{
				return this.@__1100;
			}
			set
			{
				if ((this.@__1100 != value))
				{
					this.On_1100Changing(value);
					this.SendPropertyChanging();
					this.@__1100 = value;
					this.SendPropertyChanged("_1100");
					this.On_1100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1130]", Storage="__1130", DbType="Int")]
		public System.Nullable<int> _1130
		{
			get
			{
				return this.@__1130;
			}
			set
			{
				if ((this.@__1130 != value))
				{
					this.On_1130Changing(value);
					this.SendPropertyChanging();
					this.@__1130 = value;
					this.SendPropertyChanged("_1130");
					this.On_1130Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1200]", Storage="__1200", DbType="Int")]
		public System.Nullable<int> _1200
		{
			get
			{
				return this.@__1200;
			}
			set
			{
				if ((this.@__1200 != value))
				{
					this.On_1200Changing(value);
					this.SendPropertyChanging();
					this.@__1200 = value;
					this.SendPropertyChanged("_1200");
					this.On_1200Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1230]", Storage="__1230", DbType="Int")]
		public System.Nullable<int> _1230
		{
			get
			{
				return this.@__1230;
			}
			set
			{
				if ((this.@__1230 != value))
				{
					this.On_1230Changing(value);
					this.SendPropertyChanging();
					this.@__1230 = value;
					this.SendPropertyChanged("_1230");
					this.On_1230Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1300]", Storage="__1300", DbType="Int")]
		public System.Nullable<int> _1300
		{
			get
			{
				return this.@__1300;
			}
			set
			{
				if ((this.@__1300 != value))
				{
					this.On_1300Changing(value);
					this.SendPropertyChanging();
					this.@__1300 = value;
					this.SendPropertyChanged("_1300");
					this.On_1300Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1330]", Storage="__1330", DbType="Int")]
		public System.Nullable<int> _1330
		{
			get
			{
				return this.@__1330;
			}
			set
			{
				if ((this.@__1330 != value))
				{
					this.On_1330Changing(value);
					this.SendPropertyChanging();
					this.@__1330 = value;
					this.SendPropertyChanged("_1330");
					this.On_1330Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1400]", Storage="__1400", DbType="Int")]
		public System.Nullable<int> _1400
		{
			get
			{
				return this.@__1400;
			}
			set
			{
				if ((this.@__1400 != value))
				{
					this.On_1400Changing(value);
					this.SendPropertyChanging();
					this.@__1400 = value;
					this.SendPropertyChanged("_1400");
					this.On_1400Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1430]", Storage="__1430", DbType="Int")]
		public System.Nullable<int> _1430
		{
			get
			{
				return this.@__1430;
			}
			set
			{
				if ((this.@__1430 != value))
				{
					this.On_1430Changing(value);
					this.SendPropertyChanging();
					this.@__1430 = value;
					this.SendPropertyChanged("_1430");
					this.On_1430Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1500]", Storage="__1500", DbType="Int")]
		public System.Nullable<int> _1500
		{
			get
			{
				return this.@__1500;
			}
			set
			{
				if ((this.@__1500 != value))
				{
					this.On_1500Changing(value);
					this.SendPropertyChanging();
					this.@__1500 = value;
					this.SendPropertyChanged("_1500");
					this.On_1500Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1530]", Storage="__1530", DbType="Int")]
		public System.Nullable<int> _1530
		{
			get
			{
				return this.@__1530;
			}
			set
			{
				if ((this.@__1530 != value))
				{
					this.On_1530Changing(value);
					this.SendPropertyChanging();
					this.@__1530 = value;
					this.SendPropertyChanged("_1530");
					this.On_1530Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1600]", Storage="__1600", DbType="Int")]
		public System.Nullable<int> _1600
		{
			get
			{
				return this.@__1600;
			}
			set
			{
				if ((this.@__1600 != value))
				{
					this.On_1600Changing(value);
					this.SendPropertyChanging();
					this.@__1600 = value;
					this.SendPropertyChanged("_1600");
					this.On_1600Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1630]", Storage="__1630", DbType="Int")]
		public System.Nullable<int> _1630
		{
			get
			{
				return this.@__1630;
			}
			set
			{
				if ((this.@__1630 != value))
				{
					this.On_1630Changing(value);
					this.SendPropertyChanging();
					this.@__1630 = value;
					this.SendPropertyChanged("_1630");
					this.On_1630Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jun")]
	public partial class Jun
	{
		
		private int _StaffID;
		
		private System.DateTime _Date;
		
		private System.Nullable<int> @__0900;
		
		private System.Nullable<int> @__0930;
		
		private System.Nullable<int> @__1000;
		
		private System.Nullable<int> @__1030;
		
		private System.Nullable<int> @__1100;
		
		private System.Nullable<int> @__1130;
		
		private System.Nullable<int> @__1200;
		
		private System.Nullable<int> @__1230;
		
		private System.Nullable<int> @__1300;
		
		private System.Nullable<int> @__1330;
		
		private System.Nullable<int> @__1400;
		
		private System.Nullable<int> @__1430;
		
		private System.Nullable<int> @__1500;
		
		private System.Nullable<int> @__1530;
		
		private System.Nullable<int> @__1600;
		
		private System.Nullable<int> @__1630;
		
		public Jun()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="Int NOT NULL")]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this._StaffID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0900]", Storage="__0900", DbType="Int")]
		public System.Nullable<int> _0900
		{
			get
			{
				return this.@__0900;
			}
			set
			{
				if ((this.@__0900 != value))
				{
					this.@__0900 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0930]", Storage="__0930", DbType="Int")]
		public System.Nullable<int> _0930
		{
			get
			{
				return this.@__0930;
			}
			set
			{
				if ((this.@__0930 != value))
				{
					this.@__0930 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1000]", Storage="__1000", DbType="Int")]
		public System.Nullable<int> _1000
		{
			get
			{
				return this.@__1000;
			}
			set
			{
				if ((this.@__1000 != value))
				{
					this.@__1000 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1030]", Storage="__1030", DbType="Int")]
		public System.Nullable<int> _1030
		{
			get
			{
				return this.@__1030;
			}
			set
			{
				if ((this.@__1030 != value))
				{
					this.@__1030 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1100]", Storage="__1100", DbType="Int")]
		public System.Nullable<int> _1100
		{
			get
			{
				return this.@__1100;
			}
			set
			{
				if ((this.@__1100 != value))
				{
					this.@__1100 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1130]", Storage="__1130", DbType="Int")]
		public System.Nullable<int> _1130
		{
			get
			{
				return this.@__1130;
			}
			set
			{
				if ((this.@__1130 != value))
				{
					this.@__1130 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1200]", Storage="__1200", DbType="Int")]
		public System.Nullable<int> _1200
		{
			get
			{
				return this.@__1200;
			}
			set
			{
				if ((this.@__1200 != value))
				{
					this.@__1200 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1230]", Storage="__1230", DbType="Int")]
		public System.Nullable<int> _1230
		{
			get
			{
				return this.@__1230;
			}
			set
			{
				if ((this.@__1230 != value))
				{
					this.@__1230 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1300]", Storage="__1300", DbType="Int")]
		public System.Nullable<int> _1300
		{
			get
			{
				return this.@__1300;
			}
			set
			{
				if ((this.@__1300 != value))
				{
					this.@__1300 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1330]", Storage="__1330", DbType="Int")]
		public System.Nullable<int> _1330
		{
			get
			{
				return this.@__1330;
			}
			set
			{
				if ((this.@__1330 != value))
				{
					this.@__1330 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1400]", Storage="__1400", DbType="Int")]
		public System.Nullable<int> _1400
		{
			get
			{
				return this.@__1400;
			}
			set
			{
				if ((this.@__1400 != value))
				{
					this.@__1400 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1430]", Storage="__1430", DbType="Int")]
		public System.Nullable<int> _1430
		{
			get
			{
				return this.@__1430;
			}
			set
			{
				if ((this.@__1430 != value))
				{
					this.@__1430 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1500]", Storage="__1500", DbType="Int")]
		public System.Nullable<int> _1500
		{
			get
			{
				return this.@__1500;
			}
			set
			{
				if ((this.@__1500 != value))
				{
					this.@__1500 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1530]", Storage="__1530", DbType="Int")]
		public System.Nullable<int> _1530
		{
			get
			{
				return this.@__1530;
			}
			set
			{
				if ((this.@__1530 != value))
				{
					this.@__1530 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1600]", Storage="__1600", DbType="Int")]
		public System.Nullable<int> _1600
		{
			get
			{
				return this.@__1600;
			}
			set
			{
				if ((this.@__1600 != value))
				{
					this.@__1600 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1630]", Storage="__1630", DbType="Int")]
		public System.Nullable<int> _1630
		{
			get
			{
				return this.@__1630;
			}
			set
			{
				if ((this.@__1630 != value))
				{
					this.@__1630 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mar")]
	public partial class Mar
	{
		
		private int _StaffID;
		
		private System.DateTime _Date;
		
		private System.Nullable<int> @__0900;
		
		private System.Nullable<int> @__0930;
		
		private System.Nullable<int> @__1000;
		
		private System.Nullable<int> @__1030;
		
		private System.Nullable<int> @__1100;
		
		private System.Nullable<int> @__1130;
		
		private System.Nullable<int> @__1200;
		
		private System.Nullable<int> @__1230;
		
		private System.Nullable<int> @__1300;
		
		private System.Nullable<int> @__1330;
		
		private System.Nullable<int> @__1400;
		
		private System.Nullable<int> @__1430;
		
		private System.Nullable<int> @__1500;
		
		private System.Nullable<int> @__1530;
		
		private System.Nullable<int> @__1600;
		
		private System.Nullable<int> @__1630;
		
		public Mar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="Int NOT NULL")]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this._StaffID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0900]", Storage="__0900", DbType="Int")]
		public System.Nullable<int> _0900
		{
			get
			{
				return this.@__0900;
			}
			set
			{
				if ((this.@__0900 != value))
				{
					this.@__0900 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0930]", Storage="__0930", DbType="Int")]
		public System.Nullable<int> _0930
		{
			get
			{
				return this.@__0930;
			}
			set
			{
				if ((this.@__0930 != value))
				{
					this.@__0930 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1000]", Storage="__1000", DbType="Int")]
		public System.Nullable<int> _1000
		{
			get
			{
				return this.@__1000;
			}
			set
			{
				if ((this.@__1000 != value))
				{
					this.@__1000 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1030]", Storage="__1030", DbType="Int")]
		public System.Nullable<int> _1030
		{
			get
			{
				return this.@__1030;
			}
			set
			{
				if ((this.@__1030 != value))
				{
					this.@__1030 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1100]", Storage="__1100", DbType="Int")]
		public System.Nullable<int> _1100
		{
			get
			{
				return this.@__1100;
			}
			set
			{
				if ((this.@__1100 != value))
				{
					this.@__1100 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1130]", Storage="__1130", DbType="Int")]
		public System.Nullable<int> _1130
		{
			get
			{
				return this.@__1130;
			}
			set
			{
				if ((this.@__1130 != value))
				{
					this.@__1130 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1200]", Storage="__1200", DbType="Int")]
		public System.Nullable<int> _1200
		{
			get
			{
				return this.@__1200;
			}
			set
			{
				if ((this.@__1200 != value))
				{
					this.@__1200 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1230]", Storage="__1230", DbType="Int")]
		public System.Nullable<int> _1230
		{
			get
			{
				return this.@__1230;
			}
			set
			{
				if ((this.@__1230 != value))
				{
					this.@__1230 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1300]", Storage="__1300", DbType="Int")]
		public System.Nullable<int> _1300
		{
			get
			{
				return this.@__1300;
			}
			set
			{
				if ((this.@__1300 != value))
				{
					this.@__1300 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1330]", Storage="__1330", DbType="Int")]
		public System.Nullable<int> _1330
		{
			get
			{
				return this.@__1330;
			}
			set
			{
				if ((this.@__1330 != value))
				{
					this.@__1330 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1400]", Storage="__1400", DbType="Int")]
		public System.Nullable<int> _1400
		{
			get
			{
				return this.@__1400;
			}
			set
			{
				if ((this.@__1400 != value))
				{
					this.@__1400 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1430]", Storage="__1430", DbType="Int")]
		public System.Nullable<int> _1430
		{
			get
			{
				return this.@__1430;
			}
			set
			{
				if ((this.@__1430 != value))
				{
					this.@__1430 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1500]", Storage="__1500", DbType="Int")]
		public System.Nullable<int> _1500
		{
			get
			{
				return this.@__1500;
			}
			set
			{
				if ((this.@__1500 != value))
				{
					this.@__1500 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1530]", Storage="__1530", DbType="Int")]
		public System.Nullable<int> _1530
		{
			get
			{
				return this.@__1530;
			}
			set
			{
				if ((this.@__1530 != value))
				{
					this.@__1530 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1600]", Storage="__1600", DbType="Int")]
		public System.Nullable<int> _1600
		{
			get
			{
				return this.@__1600;
			}
			set
			{
				if ((this.@__1600 != value))
				{
					this.@__1600 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1630]", Storage="__1630", DbType="Int")]
		public System.Nullable<int> _1630
		{
			get
			{
				return this.@__1630;
			}
			set
			{
				if ((this.@__1630 != value))
				{
					this.@__1630 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.May")]
	public partial class May
	{
		
		private int _StaffID;
		
		private System.DateTime _Date;
		
		private System.Nullable<int> @__0900;
		
		private System.Nullable<int> @__0930;
		
		private System.Nullable<int> @__1000;
		
		private System.Nullable<int> @__1030;
		
		private System.Nullable<int> @__1100;
		
		private System.Nullable<int> @__1130;
		
		private System.Nullable<int> @__1200;
		
		private System.Nullable<int> @__1230;
		
		private System.Nullable<int> @__1300;
		
		private System.Nullable<int> @__1330;
		
		private System.Nullable<int> @__1400;
		
		private System.Nullable<int> @__1430;
		
		private System.Nullable<int> @__1500;
		
		private System.Nullable<int> @__1530;
		
		private System.Nullable<int> @__1600;
		
		private System.Nullable<int> @__1630;
		
		public May()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffID", DbType="Int NOT NULL")]
		public int StaffID
		{
			get
			{
				return this._StaffID;
			}
			set
			{
				if ((this._StaffID != value))
				{
					this._StaffID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0900]", Storage="__0900", DbType="Int")]
		public System.Nullable<int> _0900
		{
			get
			{
				return this.@__0900;
			}
			set
			{
				if ((this.@__0900 != value))
				{
					this.@__0900 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0930]", Storage="__0930", DbType="Int")]
		public System.Nullable<int> _0930
		{
			get
			{
				return this.@__0930;
			}
			set
			{
				if ((this.@__0930 != value))
				{
					this.@__0930 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1000]", Storage="__1000", DbType="Int")]
		public System.Nullable<int> _1000
		{
			get
			{
				return this.@__1000;
			}
			set
			{
				if ((this.@__1000 != value))
				{
					this.@__1000 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1030]", Storage="__1030", DbType="Int")]
		public System.Nullable<int> _1030
		{
			get
			{
				return this.@__1030;
			}
			set
			{
				if ((this.@__1030 != value))
				{
					this.@__1030 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1100]", Storage="__1100", DbType="Int")]
		public System.Nullable<int> _1100
		{
			get
			{
				return this.@__1100;
			}
			set
			{
				if ((this.@__1100 != value))
				{
					this.@__1100 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1130]", Storage="__1130", DbType="Int")]
		public System.Nullable<int> _1130
		{
			get
			{
				return this.@__1130;
			}
			set
			{
				if ((this.@__1130 != value))
				{
					this.@__1130 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1200]", Storage="__1200", DbType="Int")]
		public System.Nullable<int> _1200
		{
			get
			{
				return this.@__1200;
			}
			set
			{
				if ((this.@__1200 != value))
				{
					this.@__1200 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1230]", Storage="__1230", DbType="Int")]
		public System.Nullable<int> _1230
		{
			get
			{
				return this.@__1230;
			}
			set
			{
				if ((this.@__1230 != value))
				{
					this.@__1230 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1300]", Storage="__1300", DbType="Int")]
		public System.Nullable<int> _1300
		{
			get
			{
				return this.@__1300;
			}
			set
			{
				if ((this.@__1300 != value))
				{
					this.@__1300 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1330]", Storage="__1330", DbType="Int")]
		public System.Nullable<int> _1330
		{
			get
			{
				return this.@__1330;
			}
			set
			{
				if ((this.@__1330 != value))
				{
					this.@__1330 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1400]", Storage="__1400", DbType="Int")]
		public System.Nullable<int> _1400
		{
			get
			{
				return this.@__1400;
			}
			set
			{
				if ((this.@__1400 != value))
				{
					this.@__1400 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1430]", Storage="__1430", DbType="Int")]
		public System.Nullable<int> _1430
		{
			get
			{
				return this.@__1430;
			}
			set
			{
				if ((this.@__1430 != value))
				{
					this.@__1430 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1500]", Storage="__1500", DbType="Int")]
		public System.Nullable<int> _1500
		{
			get
			{
				return this.@__1500;
			}
			set
			{
				if ((this.@__1500 != value))
				{
					this.@__1500 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1530]", Storage="__1530", DbType="Int")]
		public System.Nullable<int> _1530
		{
			get
			{
				return this.@__1530;
			}
			set
			{
				if ((this.@__1530 != value))
				{
					this.@__1530 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1600]", Storage="__1600", DbType="Int")]
		public System.Nullable<int> _1600
		{
			get
			{
				return this.@__1600;
			}
			set
			{
				if ((this.@__1600 != value))
				{
					this.@__1600 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1630]", Storage="__1630", DbType="Int")]
		public System.Nullable<int> _1630
		{
			get
			{
				return this.@__1630;
			}
			set
			{
				if ((this.@__1630 != value))
				{
					this.@__1630 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VwDoctors")]
	public partial class Doctors
	{
		
		private int _UserID;
		
		private string _FirstName;
		
		private string _LastName;
		
		public Doctors()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
