<?xml version="1.0" encoding="utf-8"?><Database Name="HospitalManagerDB" Class="UsersDatabase" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\HospitalManagerDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HospitalManagerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" IsDiscriminator="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Member="Username" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="UserType_User" Member="UserType" ThisKey="TypeID" OtherKey="TypeID" Type="UserType" IsForeignKey="true" />
      <Type Name="Doctor" InheritanceCode="2" />
      <Type Name="Patient" InheritanceCode="1" IsInheritanceDefault="true" />
      <Type Name="Nurse" InheritanceCode="3" />
      <Type Name="Pharmacist" InheritanceCode="4" />
    </Type>
  </Table>
  <Table Name="dbo.UserTypes" Member="UserTypes">
    <Type Name="UserType">
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Permissions" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserType_User" Member="Users" ThisKey="TypeID" OtherKey="TypeID" Type="User" />
      <Association Name="UserType_StaffMember" Member="StaffMembers" Storage="_Staffs" ThisKey="TypeID" OtherKey="TypeID" Type="StaffMember" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="StaffMembers">
    <Type Name="StaffMember">
      <Column Name="StaffID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserType_StaffMember" Member="UserType" ThisKey="TypeID" OtherKey="TypeID" Type="UserType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>